table dim_calendario
	lineageTag: 23183038-deac-44aa-aa78-bfaa67a4008a
	dataCategory: Time

	column Data
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 806f2f40-84d1-4d31-a043-ef619efa43d9
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: double
		lineageTag: f671e784-6a80-45bc-baba-988a609f4efb
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Trimestre
		dataType: double
		lineageTag: 7931f2dd-a37c-413c-986d-d368451ed82f
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MesNo
		dataType: double
		lineageTag: 5d98530f-2a75-4057-8738-8f3ddfe77083
		summarizeBy: sum
		sourceColumn: MesNo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Dia
		dataType: double
		lineageTag: d1243507-18c1-492c-a94e-32abb823fbe1
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AnoMesDia
		dataType: double
		lineageTag: b2e306a9-3310-4fbc-98d9-2941c9c5bad7
		summarizeBy: sum
		sourceColumn: AnoMesDia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Mês
		dataType: string
		lineageTag: 895c9f87-6a05-4999-a435-4bd44a7822e3
		summarizeBy: none
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column Mês/Ano
		dataType: string
		lineageTag: f151d5a4-1647-41f2-a38f-7cd538afffd8
		summarizeBy: none
		sourceColumn: Mês/Ano

		annotation SummarizationSetBy = Automatic

	column Trimestre/Ano
		dataType: string
		lineageTag: 0418038b-9c65-4907-ab4a-0a0856bfbaff
		summarizeBy: none
		sourceColumn: Trimestre/Ano

		annotation SummarizationSetBy = Automatic

	column 'Dia da Semana'
		dataType: int64
		formatString: 0
		lineageTag: 6bf869d6-4f8e-4fc8-917c-474b71c091f3
		summarizeBy: sum
		sourceColumn: Dia da Semana

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: a332a81b-9236-4281-a0c6-a8b4909d9137
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	column 'Semana do Ano'
		dataType: double
		lineageTag: 9e01440a-364a-4862-a36b-9cb9f255899a
		summarizeBy: sum
		sourceColumn: Semana do Ano

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Semana/Ano
		dataType: string
		lineageTag: 03d6e6c8-361a-40ce-a6d0-efc7bbf963ed
		summarizeBy: none
		sourceColumn: Semana/Ano

		annotation SummarizationSetBy = Automatic

	column AnoSemana
		dataType: double
		lineageTag: d716588e-728b-4556-8ee7-6dd9e1e04924
		summarizeBy: sum
		sourceColumn: AnoSemana

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AnoMes
		dataType: double
		lineageTag: de17f052-e367-4609-b3c5-f7305bd740b9
		summarizeBy: sum
		sourceColumn: AnoMes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AnoTrimestre
		dataType: double
		lineageTag: b2741c27-7ef3-491b-a2da-e873f55956c2
		summarizeBy: sum
		sourceColumn: AnoTrimestre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Futuro
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 67faf851-e3c5-487d-9c95-9d0c22ff6638
		summarizeBy: none
		sourceColumn: Futuro

		annotation SummarizationSetBy = Automatic

	column 'Dia Útil'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d0264026-8299-43dd-9fb7-e93884460af3
		summarizeBy: none
		sourceColumn: Dia Útil

		annotation SummarizationSetBy = Automatic

	column 'Offset Dia'
		dataType: double
		lineageTag: ab377c25-8f8e-4379-b04b-bc13348629ed
		summarizeBy: sum
		sourceColumn: Offset Dia

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Offset Semana'
		dataType: double
		lineageTag: bff4635f-27a0-4aef-b05d-2a3430b30ea3
		summarizeBy: sum
		sourceColumn: Offset Semana

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Offset Mês'
		dataType: double
		lineageTag: 34cc765c-cb15-428a-b3a7-97efb5ae2e41
		summarizeBy: sum
		sourceColumn: Offset Mês

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Offset Trimestre'
		dataType: double
		lineageTag: 30803f37-8abf-4c03-9126-98519ff9016a
		summarizeBy: sum
		sourceColumn: Offset Trimestre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Offset Ano'
		dataType: double
		lineageTag: c08b3d9b-b495-4f85-b38c-432d9b3c76a4
		summarizeBy: sum
		sourceColumn: Offset Ano

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Semana Completa'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b88538e4-7bed-4f35-a150-36c762dba222
		summarizeBy: none
		sourceColumn: Semana Completa

		annotation SummarizationSetBy = Automatic

	column 'Mês Completo'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 05ace9d2-bae0-46cd-a45c-f41231d6fe7d
		summarizeBy: none
		sourceColumn: Mês Completo

		annotation SummarizationSetBy = Automatic

	column 'Trimestre Completo'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ae1dbf29-9c55-4389-9758-c346efad6771
		summarizeBy: none
		sourceColumn: Trimestre Completo

		annotation SummarizationSetBy = Automatic

	column MêsAnoCurto
		dataType: string
		lineageTag: 4191fe09-d4c1-4173-9c41-44d0701f4cdd
		summarizeBy: none
		sourceColumn: MêsAnoCurto

		annotation SummarizationSetBy = Automatic

	partition dim_calendario = m
		mode: import
		source = ```
				let
				    DataMin = List.Min(mart_platform_efficiency[dt_execucao]),
				    DataMax = List.Max(mart_platform_efficiency[dt_execucao]),
				    // DataMin = #date(2023, 01, 01),
				    // DataMax = Date.From(DateTime.LocalNow()),
				    // DataMax = #date(2024, 01, 01),
				    DataInicio = Date.StartOfYear(DataMin),
				    DataFim = Date.EndOfYear(DataMax),
				    //DataInicio = #date(AnoMinDinamico, 1, 1),
				    //DataFim = #date(AnoMaxDinamico, 12, 31),
				    //DataInicio = #date(AnoMin, 1, 1),
				    //DataFim = #date(AnoMax, 12, 31),

				    DataAtual = DateTime.Date(DateTime.FixedLocalNow()),
				    QtdDias = Duration.Days(Duration.From(DataFim - DataInicio))+1,
				    Fonte = List.Dates(DataInicio,QtdDias,#duration(1,0,0,0)),
				    CriaTabela = Table.FromList(Fonte, Splitter.SplitByNothing()),
				    TipoAlterado1 = Table.TransformColumnTypes(CriaTabela,{{"Column1", type date}}),
				    RenomeiaColuna = Table.RenameColumns(TipoAlterado1,{{"Column1", "Data"}}),
				    InsereAno = Table.AddColumn(RenomeiaColuna, "Ano", each Date.Year([Data]), type number),
				    InsereTrimestre = Table.AddColumn(InsereAno, "Trimestre", each Date.QuarterOfYear([Data]), type number),
				    InsereMesNo = Table.AddColumn(InsereTrimestre, "MesNo", each Date.Month([Data]), type number),
				    InsereDia = Table.AddColumn(InsereMesNo, "Dia", each Date.Day([Data]), type number),
				    InsereAnoMesDia = Table.AddColumn(InsereDia, "AnoMesDia", each [Ano] * 10000 + [MesNo] * 100 + [Dia], type number),
				    InsereMes = Table.AddColumn(InsereAnoMesDia, "Mês", each Date.ToText([Data], "MMMM"), type text),
				    InsereMesAno = Table.AddColumn(InsereMes, "Mês/Ano", each (try(Text.Range([Mês],0,3)) otherwise [Mês]) & "/" & Number.ToText([Ano]), type text),
				    InsereTrimestreAno = Table.AddColumn(InsereMesAno, "Trimestre/Ano", each "T" & Number.ToText([Trimestre]) & "/" & Number.ToText([Ano]), type text),
				    InsereDiaSemana = Table.AddColumn(InsereTrimestreAno, "Dia da Semana", each Date.DayOfWeek([Data]), Int64.Type),
				    InsereNomeDia = Table.AddColumn(InsereDiaSemana, "Nome do Dia", each Date.ToText([Data], "dddd"), type text),
				    InsereSemanaDoAno= Table.AddColumn(InsereNomeDia, "Semana do Ano", each Date.WeekOfYear([Data]), type number),
				    InsereSemanaAno = Table.AddColumn(InsereSemanaDoAno, "Semana/Ano", each "S" & Text.From([Semana do Ano]) & "/" & Text.From([Ano]), type text ),
				    InsereAnoSemana = Table.AddColumn(InsereSemanaAno, "AnoSemana", each [Ano] * 100 + [Semana do Ano], type number),
				    InsereAnoMes = Table.AddColumn(InsereAnoSemana , "AnoMes", each [Ano] * 100 + [MesNo], type number),
				    InsereAnoTrimestre = Table.AddColumn(InsereAnoMes, "AnoTrimestre", each [Ano] * 100 + [Trimestre], type number),
				    // InsereAnoFiscal = Table.AddColumn(InsereAnoTrimestre, "Ano Fiscal", each (if MesInicioAnoFiscal = 1 then Text.From([Ano]) & "/" & Text.From([Ano] + 1) else if [MesNo]>=MesInicioAnoFiscal then Text.From([Ano]) & "/" & Text.From([Ano] + 1) else Text.From([Ano] - 1) & "/" & Text.From([Ano])), type text),
				    // InsereTrimestreFiscal = Table.AddColumn(InsereAnoFiscal, "Trimestre Fiscal", each "FT" & Text.From( Number.RoundUp( Date.Month( Date.AddMonths( [Data], - (MesInicioAnoFiscal - 1) )) / 3 )), type text),
				    // InsereMesFiscal = Table.AddColumn(InsereTrimestreFiscal, "Mês Fiscal", each if [MesNo]>=MesInicioAnoFiscal then [MesNo]-(MesInicioAnoFiscal-1) else [MesNo]+(12-MesInicioAnoFiscal+1), type text),

				    InsereFlagFuturo = Table.AddColumn(InsereAnoTrimestre, "Futuro", each not ([Data] <= Date.From(DataAtual)), type logical),
				    InsereFlagDiaUtil = Table.AddColumn(InsereFlagFuturo, "Dia Útil", each if [Dia da Semana] = 5 then false else if [Dia da Semana] = 6 then false else true, type logical),

				    InsereOffsetDia = Table.AddColumn(InsereFlagDiaUtil, "Offset Dia", each Number.From([Data] - DataAtual), type number),
				    InsereOffsetSemana = Table.AddColumn(InsereOffsetDia, "Offset Semana", each (Number.From(Date.StartOfWeek([Data]))-Number.From(Date.StartOfWeek(DateTime.LocalNow())))/7, type number),
				    InsereOffsetMes = Table.AddColumn(InsereOffsetSemana, "Offset Mês", each ((12 * Date.Year([Data])) +  Date.Month([Data])) - ((12 * Date.Year(Date.From(DataAtual))) +  Date.Month(Date.From(DataAtual))), type number),
				    InsereOffsetTrimestre = Table.AddColumn(InsereOffsetMes, "Offset Trimestre", each ((4 * Date.Year([Data])) +  Date.QuarterOfYear([Data])) - ((4 * Date.Year(Date.From(DataAtual))) +  Date.QuarterOfYear(Date.From(DataAtual))), type number),
				    InsereOffsetAno = Table.AddColumn(InsereOffsetTrimestre, "Offset Ano", each Date.Year([Data]) - Date.Year(Date.From(DataAtual)), type number),

				    // IdentificaDiaAtual = Table.SelectRows(InsereOffsetAno, each ([Data] = DataAtual)),
				    // AnoFiscalAtual = IdentificaDiaAtual{0}[Ano Fiscal],
				    // InsereOffsetAnoFiscal = Table.AddColumn(InsereOffsetAno, "Offset Ano Fiscal", each Number.From(Text.Range([Ano Fiscal],2,2)) - Number.From(Text.Range(AnoFiscalAtual,2,2)), type number),

				    InsereSemanaCompleta = Table.AddColumn(InsereOffsetAno, "Semana Completa", each Date.EndOfWeek([Data]) < Date.From(Date.EndOfWeek(DataAtual)), type logical),
				    InsereMesCompleto = Table.AddColumn(InsereSemanaCompleta, "Mês Completo", each Date.EndOfMonth([Data]) < Date.From(Date.EndOfMonth(DataAtual)), type logical),
				    InsereTrimestreCompleto = Table.AddColumn(InsereMesCompleto, "Trimestre Completo", each Date.EndOfQuarter([Data]) < Date.From(Date.EndOfQuarter(DataAtual)), type logical),
				    #"Added Custom Column" = Table.AddColumn(InsereTrimestreCompleto, "MêsAnoCurto", each Text.Combine({Text.Start(Text.Proper([Mês]), 3), "/", Text.End(Number.ToText([Ano]), 2)}))
				in
				    #"Added Custom Column"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
